### ISSUE TITLE
Missing a schematic

### ISSUE THREAD

**Issue by micooke** [mr-sneezy/Star-tracker#1]
:smile: - just being cheeky sneezy

**Comment by mr-sneezy** [comment]
Ha, I don't actually have one. For stuff this simple I can follow the circuit on the board after making it all up as I go along (and Adrian C really hates that attitude). I'll try to comment the code header better for anyone who might actually try using the massive bit of coding :)

(PS. I sort of use GIT as a place to hold my code so I can find it again too...)

**Comment by mr-sneezy** [comment]
OK, this is close to being a schematic for the stepper side at least. 
[https://arduino-info.wikispaces.com/SmallSteppers](https://arduino-info.wikispaces.com/SmallSteppers)
My fast Fwd & fast Rev switches hardly need a circuit, they are just connected to pin and GND, the pins have a 4.7k pullup on them.
